### ISSUE TITLE
Add `IS NOT NULL` to action read predicate in replay

### ISSUE THREAD

**Issue by zachschuermann** [delta-incubator/delta-kernel-rs#143] opened 2024-03-14 19:55 UTC
When reading actions in log replay we should add `add.path IS NOT NULL` and `remove.path IS NOT NULL` (and so on, for protocol/metadata too) to the predicate for pushdown to the scan for columns that survived pruning.

**Comment by nicklan** [comment] 2024-09-04 22:41
closing as a duplicate of #74

**Closed by nicklan** 2024-09-04 22:41 UTC
Labels: good first issue
